---
sudo: required
language: python
python: 2.7

services:
  - docker

install:
  - pip install ome-ansible-molecule-dependencies
  - pip install jmespath

script:
  # If PLAYBOOK is not defined assume that directory has a full
  # molecule.yml configuration file, otherwise use the default
  - >
      if [ -n "$PLAYBOOK" ]; then
          mv molecule-syntaxcheck.yml $DIRECTORY/molecule.yml;
          cd $DIRECTORY;
          mv $PLAYBOOK playbook.yml;
      else
          cd $DIRECTORY;
      fi
  - molecule test;
  # molecule-syntaxcheck.yml this doesn't run ansible-lint)
  - >
      if [ -n "$PLAYBOOK" ]; then
          ansible-lint playbook.yml;
      fi

env:
  - DIRECTORY="." PLAYBOOK=nightshade-webclients.yml
  - DIRECTORY="." PLAYBOOK=ome-demoserver.yml
  - DIRECTORY="." PLAYBOOK=ome-dundeeomero.yml
  - DIRECTORY=omero/training-server PLAYBOOK=
  - DIRECTORY=bootstrap PLAYBOOK=
  - DIRECTORY=web-proxy PLAYBOOK=
  - DIRECTORY=www PLAYBOOK=
  - DIRECTORY=k8s/postgres PLAYBOOK=
  - DIRECTORY=jupyterhub PLAYBOOK=
