---
www_folders:
  - /uod/idr/www/docs.openmicroscopy.org
  - /uod/idr/www/downloads.openmicroscopy.org
# Public image format folders
# All keys of this dictionary are expected to be a valid format folder and
# have a subfolder called public containing the public sample images
public_folders:
  amira: 'AmiraMesh'
  bdv: 'BDV'
  becker-hickl-spc: 'SPC-FIFO'
  cellomics: 'Cellomics'
  cellh5: 'CellH5'
  cellworx: 'CellWorX'
  columbus: 'PerkinElmer-Columbus'
  deltavision: 'DV'
  dicom: 'DICOM'
  ecat7: 'ECAT7'
  flex: 'Flex'
  fv1000: 'Olympus-FluoView'
  gatan: 'Gatan'
  hamamatsu: 'Hamamatsu-NDPI'
  hamamatsu-vms: 'Hamamatsu-VMS'
  ics: 'ICS'
  incell3000: 'InCell3000'
  incell: 'InCell2000'
  imaris: 'Imaris-IMS'
  klb: 'KLB'
  leica-lif: 'Leica-LIF'
  leica-scn: 'Leica-SCN'
  leica-xlef-lof: 'Leica-XLEF'
  leo: 'LEO'
  metaxpress: 'MetaXpress'
  micromanager: 'Micro-Manager'
  mrc: 'MRC'
  nd2: 'ND2'
  nifti: 'NIfTI'
  nrrd: 'NRRD'
  obf: 'OBF'
  olympus-oir: 'Olympus-OIR'
  ome-xml: 'OME-XML'
  ome-tiff: 'OME-TIFF'
  perkinelmer-operetta: 'PerkinElmer-Operetta'
  png: 'PNG'
  svs: 'SVS'
  tiff: 'TIFF'
  trestle: 'Trestle'
  ventana: 'Ventana'
  vectra-qptiff: 'Vectra-QPTIFF'
  zeiss-czi: 'Zeiss-CZI'
# List containing special public images/folders that do not meet the standard
# layout above
special_public_folders:
  - { src: '../../../../repos/curated/samples/carlos/big.tiff', dest: 'gateway_tests/big.tiff'}
  - { src: '../../../../repos/curated/samples/ome/CHOBI_d3d.dv', dest: 'gateway_tests/CHOBI_d3d.dv'}
  - { src: '../../../../repos/curated/samples/ome/tinyTest.d3d.dv',
      dest: 'gateway_tests/tinyTest.d3d.dv' }
  - { src: '../../../../repos/curated/cellomics/public/', dest: 'HCS/BBBC'}
  - { src: '../../../../repos/curated/incell/public/', dest: 'HCS/INCELL2000'}
  - { src: '../../../../repos/curated/perkinelmer-operetta/public/', dest: 'HCS/Operetta'}
  - { src: '../../../repos/curated/zip/u-track/', dest: 'u-track'}
